COUNTRY_CHOICES = [
    ('Select', ''),
    ('col', 'Colombia'),
    ('bra', 'Brazil'),
    ('arg', 'Argentina'),
    ('can', 'Canada'),
    ('afg', 'Afghanistan'),
    ('dza', 'Algeria'),
    ('and', 'Andorra'),
    ('arm', 'Armenia'),
    ('abw', 'Aruba'),
    ('aus', 'Australia'),
    ('aut', 'Austria'),
    ('bel', 'Belgium'),
    ('cmr', 'Cameroon'),
    ('chl', 'Chile'),
    ('chn', 'China'),
    ('cri', 'Costa rica'),
    ('hrv', 'Croatia'),
    ('dom', 'Dominican Republic'),
    ('slv', 'El Salvador'),
    ('est', 'Estonia'),
    ('fra', 'France'),
    ('deu', 'Germany'),
    ('grc', 'Greece'),
    ('isl', 'Iceland'),
    ('ind', 'India'),
    ('irq', 'Iraq'),
    ('isr', 'Israel'),
    ('jpn', 'Japan'),
    ('ita', 'Italy'),
    ('kor', 'Korea'),
    ('lux', 'Luxembourg'),
    ('mex', 'Mexico'),
    ('mco', 'Monaco'),
    ('nam', 'Namibia'),
    ('nic', 'Nicaragua'),
    ('nga', 'Nigeria'),
    ('nor', 'Norway'),
    ('pan', 'Panama'),
    ('per', 'Peru'),
    ('phl', 'Philippines'),
    ('pol', 'Poland'),
    ('prt', 'Portugal'),
    ('pri', 'Puerto Rico'),
    ('qat', 'Qatar'),
    ('rus', 'Russia'),
    ('sau', 'Saudi Arabia'),
    ('srb', 'Serbia'),
    ('sgp', 'Singapore'),
    ('esp', 'Spain'),
    ('che', 'Switzerland'),
    ('tur', 'Turkey'),
    ('uga', 'Uganda'),
    ('usa', 'United states of america'),
    ('irq', 'Iraq'),
    ('ury', 'Uruguay'),
    ('ven', 'Venezuela'),
    ('vnm', 'Vietnam'),
    ('zwe', 'Zimbabwe')
]
